/**
 * The checker's rules about parents, bugs and pins, run on small projects built
 * in a temporary directory. A project's canon is what the checker reads, so each
 * case writes a `CANON.md` and a test file and runs `check` over them.
 *
 * This file tests the checker's own tooling, not a project's canon, so it lives
 * outside any declared suite directory and carries no `@canon` tag.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';

const CLI = join(dirname(fileURLToPath(import.meta.url)), 'cli.ts');

const DIRS: string[] = [];
afterEach(() => {
  for (const dir of DIRS.splice(0)) rmSync(dir, { recursive: true, force: true });
});

const HEAD = `# Canon

<!-- toc:begin — generated by \`canon generate\`; edits are overwritten -->
<!-- toc:end -->

## @axiom a-program-means-one-thing

> A program means one thing.
`;

/** A canon document, as the units below the axiom. */
const canon = (units: string): string => `${HEAD}\n${units}`;

/**
 * Builds a project of one canon document and one test file, runs `check` over
 * it, and returns each finding that has any entries, with its count.
 */
function check(document: string, test: string): Record<string, number> {
  const dir = mkdtempSync(join(tmpdir(), 'canon-check-'));
  DIRS.push(dir);
  mkdirSync(join(dir, 'test', 'canon'), { recursive: true });
  writeFileSync(
    join(dir, 'package.json'),
    JSON.stringify({
      canon: { documents: ['CANON.md'], suites: 'test/canon', sources: ['test'], command: 'canon' }
    })
  );
  writeFileSync(join(dir, 'CANON.md'), document);
  writeFileSync(join(dir, 'test', 'canon', 'a.test.ts'), test);
  spawnSync(process.execPath, [CLI, 'generate'], { cwd: dir });
  const run = spawnSync(process.execPath, [CLI, 'check'], { cwd: dir, encoding: 'utf8' });
  const counts: Record<string, number> = {};
  for (const line of run.stdout.split('\n')) {
    const found = /^(\S+) — .*: (\d+)$/.exec(line);
    if (found && Number(found[2]) > 0) counts[found[1] as string] = Number(found[2]);
  }
  return counts;
}

const LEAF = `
### @spec a-leaf-says-one-thing

> A leaf says one thing.
`;

const PARENT = `
### @spec a-parent-names-its-cases

> A parent names its cases.

#### @spec the-first-case-holds

> The first case holds.
`;

const tagged = (id: string, mark = 'it'): string => `
/**
 * @canon ${id}
 */
${mark}('checks it', () => {});
`;

describe('a spec that holds nested specs', () => {
  it('owes no test of its own, and the leaf under it owes one', () => {
    expect(check(canon(PARENT), tagged('spec-the-first-case-holds'))).toEqual({});
  });

  it('is a finding when a test cites it, which belongs to its leaf', () => {
    const found = check(canon(PARENT), tagged('spec-a-parent-names-its-cases') + tagged('spec-the-first-case-holds'));
    expect(found['parent-cited']).toBe(1);
  });

  it('leaves its leaf untested when only the parent is cited', () => {
    const found = check(canon(PARENT), tagged('spec-a-parent-names-its-cases'));
    expect(found['parent-cited']).toBe(1);
    expect(found['untested']).toBeGreaterThan(0);
  });
});

describe('a bug', () => {
  const BUG = (issue: boolean) => `${LEAF}
#### @bug the-leaf-breaks

> The code does another thing.
${issue ? '\nIssue: #7\n' : ''}`;

  it('is clean when it names an issue and a test marked to fail cites it', () => {
    expect(check(canon(BUG(true)), tagged('bug-the-leaf-breaks', 'it.fails'))).toEqual({});
  });

  it('is a finding when it names no issue', () => {
    const found = check(canon(BUG(false)), tagged('bug-the-leaf-breaks', 'it.fails'));
    expect(found['untracked-bug']).toBe(1);
  });

  it('is a finding when a test cites it without being marked to fail', () => {
    const found = check(canon(BUG(true)), tagged('bug-the-leaf-breaks'));
    expect(found['unpinned-bug']).toBe(1);
  });

  it('counts as a test of the spec it breaks, which stays a leaf', () => {
    const found = check(canon(BUG(true)), tagged('bug-the-leaf-breaks', 'it.fails'));
    expect(found['untested']).toBeUndefined();
    expect(found['parent-cited']).toBeUndefined();
  });

  it('makes a test marked to fail a finding when it cites no bug or exception', () => {
    const found = check(canon(LEAF), tagged('spec-a-leaf-says-one-thing') + tagged('spec-a-leaf-says-one-thing', 'it.fails'));
    expect(found['fails-without-bug']).toBe(1);
  });
});
