/**
 * The marker protocol of the canon documents' generated regions. What is pinned
 * here is the tail: a begin marker carrying a note must still be found by its
 * region name, and must come back canonical after a rewrite.
 *
 * This file tests the checker's own tooling, not a project's canon, so it lives
 * outside any declared suite directory and carries no `@canon` tag.
 */
import { describe, expect, it } from 'vitest';
import { beginMarker, regionAt, replaceRegion } from './regions.ts';

const TOC_END = '<!-- toc:end -->';

describe('a generated region', () => {
  it('is found by a begin marker whatever note it carries', () => {
    const src = `# Doc\n\n<!-- toc:begin — generated by \`some older command\` -->\nold\n${TOC_END}\n`;
    const at = regionAt(src, 'toc', TOC_END);
    expect(at).toBeDefined();
    expect(src.slice(at?.body, at?.to).trim()).toBe('old');
  });

  it('comes back with the canonical marker, note and all, when rewritten', () => {
    const src = `# Doc\n\n<!-- toc:begin -->\nold\n${TOC_END}\n`;
    const written = replaceRegion(src, 'toc', TOC_END, '- [`rule-x`](#rule-x)');
    expect(written).toBe(
      `# Doc\n\n${beginMarker('toc')}\n- [\`rule-x\`](#rule-x)\n${TOC_END}\n`
    );
  });

  it('does not take a bare comment, or another region, for its marker', () => {
    expect(
      regionAt(`<!-- a note -->\nx\n${TOC_END}`, 'toc', TOC_END)
    ).toBeUndefined();
    expect(
      regionAt(`${beginMarker('kinds')}\nx\n${TOC_END}`, 'toc', TOC_END)
    ).toBeUndefined();
  });

  it('is undefined when a marker is missing or the pair is inverted', () => {
    expect(
      regionAt(`${beginMarker('toc')}\nx\n`, 'toc', TOC_END)
    ).toBeUndefined();
    expect(
      regionAt(`${TOC_END}\n${beginMarker('toc')}`, 'toc', TOC_END)
    ).toBeUndefined();
    expect(replaceRegion('nothing here', 'toc', TOC_END, 'x')).toBeUndefined();
  });
});
