/*
 * regions.ts — the generated regions of the canon documents: the HTML-comment
 * markers that delimit them, and the read/write pair `cli.ts` drives them with.
 *
 * The begin marker carries the maintenance note, rather than a visible line
 * inside the region. Its audience is whoever is about to edit the raw file, and
 * that person reads HTML comments; a reader of the rendered document only wants
 * the index. Every `generate` rewrites the marker, so renaming the command
 * cannot leave the note behind as rotted advice.
 */

/** The begin marker of a generated region, note and all. */
export const beginMarker = (region: string): string =>
  `<!-- ${region}:begin — generated by \`canon generate\`; edits are overwritten -->`;

/**
 * Matches the begin marker of exactly `region`, whatever note it carries: the
 * region name still identifies the region, only the tail is free.
 */
const beginPattern = (region: string): RegExp =>
  new RegExp(`<!--[ \\t]*${region}:begin\\b[^>]*-->`);

/**
 * The extent of a generated region: where its begin marker starts, where its
 * body starts, and where its end marker starts. Undefined when either marker is
 * missing, or they are the wrong way round.
 */
export function regionAt(
  text: string,
  region: string,
  end: string
): { at: number; body: number; to: number } | undefined {
  const m = beginPattern(region).exec(text);
  const to = text.indexOf(end);
  if (m === null || to === -1 || to < m.index) return undefined;
  return { at: m.index, body: m.index + m[0].length, to };
}

/**
 * `text` with the region's body replaced and its begin marker rewritten to the
 * canonical form, so the note is regenerated with the body it heads; undefined
 * when the region's markers are not both there.
 */
export function replaceRegion(
  text: string,
  region: string,
  end: string,
  body: string
): string | undefined {
  const at = regionAt(text, region, end);
  if (at === undefined) return undefined;
  return `${text.slice(0, at.at)}${beginMarker(region)}\n${body}\n${text.slice(at.to)}`;
}
