/**
 * `check` holds each bug's issue to the tracker. The tracker here is a stub
 * server on a local port that answers the way GitHub and GitLab answer, so the
 * requests the checker makes are the ones a real tracker would get.
 *
 * This file tests the checker's own tooling, not a project's canon, so it lives
 * outside any declared suite directory and carries no `@canon` tag.
 */
import { spawn, spawnSync } from 'node:child_process';
import { createServer, type IncomingMessage, type Server } from 'node:http';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { issueRefs, trackerProblems } from './tracker.ts';

const CLI = join(dirname(fileURLToPath(import.meta.url)), 'cli.ts');

let server: Server;
let origin: string;
/** Every request the stub received, as `METHOD path` and the headers that matter. */
let requests: Array<{ line: string; auth?: string; privateToken?: string }>;
/** What the stub answers for a path, by exact `path?query`. */
let routes: Record<string, { status: number; body?: unknown }>;
const DIRS: string[] = [];

beforeEach(async () => {
  requests = [];
  routes = {};
  server = createServer((request: IncomingMessage, response) => {
    requests.push({
      line: `${request.method} ${request.url}`,
      auth: request.headers.authorization,
      privateToken: request.headers['private-token'] as string | undefined
    });
    const route = routes[request.url ?? ''] ?? { status: 404 };
    response.writeHead(route.status, { 'content-type': 'application/json' });
    response.end(JSON.stringify(route.body ?? {}));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  origin = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
});

afterEach(async () => {
  await new Promise<void>((resolve) => server.close(() => resolve()));
  for (const dir of DIRS.splice(0)) rmSync(dir, { recursive: true, force: true });
});

const CANON = (issues: string[]): string => `# Canon

<!-- toc:begin — generated by \`canon generate\`; edits are overwritten -->
<!-- toc:end -->

## @axiom a-program-means-one-thing

> A program means one thing.

### @spec a-leaf-says-one-thing

> A leaf says one thing.

${issues
  .map(
    (issue, at) => `#### @bug the-leaf-breaks-${at}

> The code does another thing.

Issue: ${issue}
`
  )
  .join('\n')}`;

const TEST = (count: number): string =>
  Array.from({ length: count }, (_, at) => `/**\n * @canon bug-the-leaf-breaks-${at}\n */\nit.fails('pins ${at}', () => {});\n`).join('\n');

interface Run {
  code: number | null;
  out: string;
}

/** A project with `issues` as the issue line of one bug each, checked with `args`. */
async function check(
  issues: string[],
  tracker: Record<string, unknown> | undefined,
  options: { env?: Record<string, string>; args?: string[] } = {}
): Promise<Run> {
  const dir = mkdtempSync(join(tmpdir(), 'canon-tracker-'));
  DIRS.push(dir);
  mkdirSync(join(dir, 'test', 'canon'), { recursive: true });
  writeFileSync(
    join(dir, 'package.json'),
    JSON.stringify({ canon: { documents: ['CANON.md'], suites: 'test/canon', sources: ['test'], command: 'canon', tracker } })
  );
  writeFileSync(join(dir, 'CANON.md'), CANON(issues));
  writeFileSync(join(dir, 'test', 'canon', 'a.test.ts'), TEST(issues.length));
  const env = { ...process.env, GITHUB_TOKEN: '', GITLAB_TOKEN: '', ...options.env };
  spawnSync(process.execPath, [CLI, 'generate'], { cwd: dir, env });
  const child = spawn(process.execPath, [CLI, 'check', ...(options.args ?? [])], { cwd: dir, env });
  let out = '';
  child.stdout.on('data', (chunk) => (out += chunk));
  child.stderr.on('data', (chunk) => (out += chunk));
  const code = await new Promise<number | null>((resolve) => child.on('close', resolve));
  return { code, out };
}

const github = (extra: Record<string, unknown> = {}) => ({ kind: 'github', repo: 'acme/app', host: origin, ...extra });
const gitlab = (extra: Record<string, unknown> = {}) => ({ kind: 'gitlab', project: 'acme/app', host: origin, ...extra });

describe('a GitHub tracker', () => {
  it('is clean when each issue exists and is open, and sends the token', async () => {
    routes['/api/v3/repos/acme/app/issues/1'] = { status: 200, body: { state: 'open' } };
    const run = await check(['#1'], github(), { env: { GITHUB_TOKEN: 'secret' } });
    expect(run.out).toContain('clean');
    expect(requests).toEqual([{ line: 'GET /api/v3/repos/acme/app/issues/1', auth: 'Bearer secret', privateToken: undefined }]);
  });

  it('reports an issue that is closed', async () => {
    routes['/api/v3/repos/acme/app/issues/2'] = { status: 200, body: { state: 'closed' } };
    const run = await check(['#2'], github(), { env: { GITHUB_TOKEN: 'secret' } });
    expect(run.code).toBe(1);
    expect(run.out).toMatch(/closed-issue[^\n]*: 1\n {2}· CANON\.md#bug-the-leaf-breaks-0 names #2, which is closed/);
  });

  it('reports an issue the tracker does not hold, when the token was sent', async () => {
    const run = await check(['#3'], github(), { env: { GITHUB_TOKEN: 'secret' } });
    expect(run.out).toMatch(/missing-issue[^\n]*: 1\n {2}· CANON\.md#bug-the-leaf-breaks-0 names #3, which acme\/app does not hold/);
  });

  it('reports a pull request named as an issue', async () => {
    routes['/api/v3/repos/acme/app/issues/4'] = { status: 200, body: { state: 'open', pull_request: {} } };
    const run = await check(['#4'], github(), { env: { GITHUB_TOKEN: 'secret' } });
    expect(run.out).toContain('names #4, which is a pull request');
  });

  it('cannot tell a private project from a missing issue without a token, and says so', async () => {
    const run = await check(['#5'], github());
    expect(run.code).toBe(1);
    expect(run.out).toMatch(/unreachable-tracker[^\n]*: 1/);
    expect(run.out).toContain('no token in GITHUB_TOKEN');
    expect(run.out).not.toMatch(/missing-issue[^\n]*: [1-9]/);
  });

  it('reads the token from the variable the project names', async () => {
    routes['/api/v3/repos/acme/app/issues/6'] = { status: 200, body: { state: 'open' } };
    const run = await check(['#6'], github({ tokenEnv: 'WORK_TOKEN' }), { env: { WORK_TOKEN: 'other' } });
    expect(run.out).toContain('clean');
    expect(requests[0]?.auth).toBe('Bearer other');
  });
});

describe('a GitLab tracker', () => {
  const list = (iids: number[], states: Record<number, string>) => ({
    status: 200,
    body: iids.filter((iid) => iid in states).map((iid) => ({ iid, state: states[iid] }))
  });

  it('asks for every issue of the project in one request, and sends the token as a private token', async () => {
    routes['/api/v4/projects/acme%2Fapp/issues?iids[]=1&iids[]=2&iids[]=3&per_page=100'] = list([1, 2, 3], { 1: 'opened', 2: 'closed' });
    const run = await check(['#1', '#2', '#3'], gitlab(), { env: { GITLAB_TOKEN: 'secret' } });
    expect(requests).toHaveLength(1);
    expect(requests[0]?.privateToken).toBe('secret');
    expect(run.out).toContain('names #2, which is closed');
    expect(run.out).toContain('names #3, which acme/app does not hold');
    expect(run.out).not.toContain('names #1');
  });

  it('reports a project the token cannot read once, however many bugs name it', async () => {
    const run = await check(['#1', '#2'], gitlab());
    expect(run.code).toBe(1);
    expect(run.out).toMatch(/unreachable-tracker[^\n]*: 1\n {2}· acme\/app answered 404: no token in GITLAB_TOKEN[^\n]*\(2 bug\(s\)/);
  });

  it('takes a numeric project id', async () => {
    routes['/api/v4/projects/42/issues?iids[]=9&per_page=100'] = list([9], { 9: 'opened' });
    const run = await check(['#9'], gitlab({ project: 42 }), { env: { GITLAB_TOKEN: 'secret' } });
    expect(run.out).toContain('clean');
  });

  it('holds an issue named by its address to the project that address names', async () => {
    routes['/api/v4/projects/other%2Frepo/issues?iids[]=7&per_page=100'] = list([7], { 7: 'opened' });
    const run = await check([`${origin}/other/repo/-/issues/7`], gitlab(), { env: { GITLAB_TOKEN: 'secret' } });
    expect(run.out).toContain('clean');
  });
});

describe('a project with a tracker', () => {
  it('asks nothing under --offline, and says so', async () => {
    const run = await check(['#1'], github(), { args: ['--offline'] });
    expect(requests).toEqual([]);
    expect(run.out).toContain('issues: not checked (--offline)');
    expect(run.out).toContain('clean');
  });

  it('reports a tracker that cannot be reached', async () => {
    const closed = origin;
    await new Promise<void>((resolve) => server.close(() => resolve()));
    const run = await check(['#1'], { kind: 'github', repo: 'acme/app', host: closed });
    server = createServer();
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    expect(run.code).toBe(1);
    expect(run.out).toMatch(/unreachable-tracker[^\n]*: 1\n {2}· .*could not be reached/);
  });

  it('reports a tracker field that is not usable', async () => {
    const run = await check(['#1'], { kind: 'github' });
    expect(run.out).toContain('a github tracker needs "repo": "owner/name"');
  });
});

describe('a project with no tracker', () => {
  it('accepts a bare issue number, as before, and prints no tracker findings', async () => {
    const run = await check(['#1'], undefined);
    expect(run.out).toContain('clean');
    expect(run.out).not.toContain('closed-issue');
    expect(requests).toEqual([]);
  });
});

describe('the issues a bug names', () => {
  const tracker = { kind: 'gitlab', project: 'acme/app', host: 'https://git.example.com' } as const;

  it('are bare numbers of the configured tracker, and addresses of their own', () => {
    const refs = issueRefs('Issue: #12, and https://git.example.com/acme/lib/-/issues/3', tracker);
    expect(refs.map((r) => `${r.project}#${r.number}`)).toEqual(['acme/lib#3', 'acme/app#12']);
  });

  it('take a GitHub address for a GitHub issue, wherever the configured tracker is', () => {
    const [ref] = issueRefs('see https://github.com/acme/app/issues/8', tracker);
    expect(ref).toMatchObject({ kind: 'github', project: 'acme/app', number: 8 });
  });

  it('ignore a number that is not an issue number', () => {
    expect(issueRefs('a&#38; entity and abc#4', tracker)).toEqual([]);
  });

  it('name what is wrong with a tracker field', () => {
    expect(trackerProblems({ kind: 'gitlab' })).toEqual(['a gitlab tracker needs "project": the path or the numeric id']);
    expect(trackerProblems({ kind: 'gitlab', project: 'a/b' })).toEqual([]);
  });
});
